### PR TITLE
AkaiApcKey25 & Docs

### PR DESCRIPTION
**Pull request by manucontrovento**
Here in attachment the controller script and docs about it.

My suggestion, if possible, is to create in SB' root directory, a subdir named e.g. "controllers" in which to put all sbm files and docs

[AKAI_APC_Key25.sbm.zip](https://github.com/Vampouille/superboucle/files/4444356/AKAI_APC_Key25.sbm.zip)

[AKAI_APC_Key25_SB-en.pdf](https://github.com/Vampouille/superboucle/files/4444366/AKAI_APC_Key25_SB-en.pdf)
[AKAI_APC_Key25_SB-it.pdf](https://github.com/Vampouille/superboucle/files/4444367/AKAI_APC_Key25_SB-it.pdf)

### CODE REVIEW

**Comment by manucontrovento** [comment]
I'll manage it in my repository

**Comment by manucontrovento** [comment]
Here in attachment the controller script and docs about it.

My suggestion, if possible, is to create in SB' root directory, a subdir named e.g. "controllers" in which to put all sbm files and docs

[/controllers/AKAI_APC_Key25.sbm.zip](https://github.com/Vampouille/superboucle/files/4444369/AKAI_APC_Key25.sbm.zip)

[AKAI_APC_Key25_SB-en.pdf](https://github.com/Vampouille/superboucle/files/4444370/AKAI_APC_Key25_SB-en.pdf)
[AKAI_APC_Key25_SB-it.pdf](https://github.com/Vampouille/superboucle/files/4444371/AKAI_APC_Key25_SB-it.pdf)

**Comment by Vampouille** [comment]
@manucontrovento I'm ok with the `controller` subdir. Can you modify this pull request to create this subdir and add sbm file for your Akai controller ?

**Comment by manucontrovento** [comment]
As requested I created a new file in /controller/ subdir
 You could download from here  the PDF files if you want to

**Pull request closed without merging**
