### PR TITLE
Playlist editor from HD

### PR DESCRIPTION
**Pull request by IARI**
this PR is addressing 
- https://github.com/sonejostudios/superboucle/issues/5 and 
- https://github.com/sonejostudios/superboucle/issues/27

### CODE REVIEW

**Comment by IARI** [comment]
@Vampouille thank you for merging the scene-manager! :+1:

Now this one is the final PR from the changes I had made last summer.

Now here is a meta question:
Is it more comfortable for you if I 
- split changes in smaller PR's like I have done with the last three?
- or would you prefer one bigger PR?

I hope we'll get midi bindings for the scene manager done until LAC Berlin in April :)

**Comment by Vampouille** [comment]
I would prefer small PR, thanks !

**Comment by IARI** [comment]
@Vampouille I'll gladly split everything up in tiny easily digestible peaces :)

Our goal would be to integrate midi binding for scenes until LAC Berlin in April.

So far a sketch of a roadmap after this one would be to make 3 small pull requests and finally add the midi binding in a 4th PR.

Do you think we can do that until april? (sadly I'll have to work full time in march)

Also: is there anything that needs to be done with this PR before it can be merged?

**Comment by Vampouille** [comment]
Hello, 

I also began a full time work, as you can see with my latency to review your push requests ! It would be nice to meet you in Berlin. After a quick review, I think I can merge your PR. If you want to make a demo, then we need to fully test new code.

**Pull request merged**
