### PR TITLE
Several features added

### PR DESCRIPTION
**Pull request by IARI**
Added features including:
-playlist
-nameable out-ports per song
-mutegroups and outports per clip
A few bugfixxes including:
-bpm and beats_per_bar were not saved in the song file

Unfortunately Vince didnt CC me in the email conversation, otherwise i would have added the featurelist he compiled there.
He mentioned, you just wanted a pull request for everything.

### CODE REVIEW

**Comment by Vampouille** [comment]
did you fix bug on mute group ?

https://github.com/Vampouille/superboucle/compare/master...sonejostudios:master#diff-d7ea909974912b726b076cf771f912aaR122 
 replace line 122 by :

    c.state = Clip.STOPPING if c.state == Clip.START
    c.state = Clip.STOP if c.state == Clip.STARTING

should fix bug

**Comment by Vampouille** [comment]
Can you restore automatic connection to souncard output ? By default, superboucle should connect to output, if you need specific connection we need to add an option on command line `--no-auto-connect` or gui.

**Comment by IARI** [comment]
I added a checkbox to the port manager. Its not yet connected, but im working on it :)
When it is checked, the main-port is supposed to automatically connect to the first physical channels.

**Comment by IARI** [comment]
I just finished my last idea: added a session config in 49761fdcc17eb6f16249bcd9d6b5b91929bc4ea0

Now I'm going to connect the check-box and then I'll issue a new Pull request.

**Pull request closed without merging**
